---
- hosts: k8s_cluster
  tasks: []
  roles:
    - role: cluster_defaults
      tags: defaults
    - role: remove_kubespray_host_dns_settings
      tags: remove-kubespray-host-dns-settings
      when:
        - remove_kubespray_host_dns_settings | default(false) | bool
    - role: nfd_install
      tags: nfd
      when: nfd_enabled | default(true) | bool
    - role: operator_framework
      tags: operator-framework
      when:
        - intel_ethernet_operator_enabled | default(false) | bool or
          intel_sriov_fec_operator_enabled | default(false) | bool
    - role: intel_ethernet_operator
      tags: intel-ethernet-operator
      when:
        - intel_ethernet_operator_enabled | default(false) | bool
    - role: sriov_dp_install
      tags: sriov-net-dp
      when:
        - sriov_net_dp_enabled | default(false) | bool
        - not sriov_network_operator_enabled | default(true) | bool
    - role: sriov_network_operator_install
      tags: sriov-network-operator
      when:
        - sriov_network_operator_enabled | default(true) | bool
        - not sriov_net_dp_enabled | default(false) | bool
        - not sriov_cni_enabled | default(false) | bool
    - role: kube_prometheus
      when:
        - prometheus_operator | default(false) | bool
    - role: collectd_install
      tags: monitoring
      when:
        - collectd_enabled | default(false) | bool
        - not (telegraf_enabled | default(true) | bool)
      vars:
        collectd_profile: basic
    - role: telegraf_install
      when:
        - telegraf_enabled | default(true) | bool
        - not (collectd_enabled | default(false) | bool)
      tags: monitoring
      vars:
        telegraf_profile: basic
    - role: cndp_install
      tags: cndp
      when:
        - cndp_enabled | default(false) | bool
        - (ansible_distribution == "Ubuntu" and ansible_distribution_version >= "20.04") or
          (ansible_os_family == "RedHat" and ansible_distribution_version >= "8.5")
    - role: cndp_dp_install
      tags: cndp-dp
      when:
        - cndp_dp_enabled | default(false) | bool
        - (ansible_distribution == "Ubuntu" and ansible_distribution_version >= "20.04") or
          (ansible_os_family == "RedHat" and ansible_distribution_version >= "8.5")

  environment:
    - "{{ proxy_env | d({}) }}"
    - REGISTRY_AUTH_FILE: "{{ registry_containerd }}"
  any_errors_fatal: true

- hosts: kube_node
  tasks: []
  roles:
    - role: cluster_defaults
      tags: defaults
    - role: sriov_cni_install
      when:
        - sriov_cni_enabled | default(false) | bool
        - not sriov_network_operator_enabled | default(true) | bool
      tags: sriov-cni
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

- hosts: kube_control_plane
  tasks: []
  roles:
    - role: net_attach_defs_create
      tags: net-attach-defs
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true
